Proposal for EXT_texture_norm16_dom_source
KhronosGroup/WebGL pull request #3191
Opened 2020-12-04 00:34 UTC by shrekshao

Draft a proposal for EXT_texture_norm16_dom_source based on discussions at WebGL WG 2020-12-03.
There are a lot of details that needs refining such as image source format other than PNG with 8<c<16 bits per channel, potential query function for various image source format, channel mapping, 8bit img src requantization etc.

2020-12-04 23:10 UTC, kenrussell requested changes

2020-12-04 23:10 UTC, kenrussell commented on extensions/proposals/EXT_texture_norm16_dom_source/extension.xml
> +      <code>RGB16_EXT</code>, and <code>RGBA16_EXT</code> would throw a DOMException.
would throw -> throw

2020-12-04 23:10 UTC, kenrussell commented on extensions/proposals/EXT_texture_norm16_dom_source/extension.xml
> +      would result in channel expanding where red, green, blue channels are populated with 0 and alpha channel are populated with 1.
would -> will
expanding -> expansion
green, blue -> green, and blue
alpha channel are -> alpha channel is

Do you want to say:
1 (0xffff)
?

2020-12-04 23:10 UTC, kenrussell commented on extensions/proposals/EXT_texture_norm16_dom_source/extension.xml
> +      <feature>Uploading <code>ImageBitmap</code> or <code>HTMLImageelement</code> with fewer channels than that indicated by internal formats
Capitalize "e" in element.
internal formats -> the internal format

2020-12-04 23:10 UTC, kenrussell commented on extensions/proposals/EXT_texture_norm16_dom_source/extension.xml
> +      Uploading image sources with more channels that that indicated by internal format would result in channel clamping.
internal format -> the internal format
would result -> result

2020-12-04 23:10 UTC, kenrussell commented on extensions/proposals/EXT_texture_norm16_dom_source/extension.xml
> +      </feature>
Please mention something like that if this extension is enabled, it automatically enables EXT_texture_norm16 as well.

2020-12-04 23:10 UTC, kenrussell commented on extensions/proposals/EXT_texture_norm16_dom_source/extension.xml
> +interface EXT_texture_norm16_dom_source {
Let's remove the enums from this extension and expect users to fetch the EXT_texture_norm16 extension to get them.

2020-12-05 00:42 UTC, shrekshao commented
Thanks for the review! Fixed the issue.

2020-12-08 05:22 UTC, kenrussell approved these changes
This looks good. Nice work @shrekshao . Let's merge it in order to get further feedback.

2020-12-08 05:22 UTC, merged