s/NoInterfaceObject/Exposed=Window, LegacyNoInterfaceObject/ in exten…
KhronosGroup/WebGL pull request #3279
Opened 2021-04-15 19:25 UTC by jdashg

…sions/.

2021-04-16 08:13 UTC, foolip approved these changes
Yay! (Don't have write access, just expressing support.)

2021-04-18 07:06 UTC, kenrussell requested changes
Thanks for taking care of this; one mechanical change needed throughout.

2021-04-18 07:06 UTC, kenrussell commented on extensions/EXT_texture_compression_bptc/extension.xml
> +[Exposed=Window, LegacyNoInterfaceObject]
WebGL can be used on workers; throughout this needs to be:
  Exposed=(Window,Worker)
like in the WebGL 1.0 and 2.0 specs.

2021-04-20 23:16 UTC, kenrussell approved these changes
Thanks for taking care of this; looks good!

2021-04-20 23:16 UTC, merged