Add test of toDataURL after compositing the WebGL canvas.
KhronosGroup/WebGL pull request #3293
Opened 2021-06-17 19:51 UTC by kenrussell

Regression test for http://crbug.com/1216489 , where this path was
broken in Chromium when using SwiftShader.

Test passes in Firefox Nightly and Safari.

2021-06-17 19:53 UTC, kenrussell commented
@jdashg @shrekshao please review.

@kripken FYI.

2021-06-17 21:09 UTC, shrekshao approved these changes
LGTM

2021-06-17 23:00 UTC, jdashg approved these changes

2021-06-17 23:00 UTC, jdashg requested changes
You need to add it to the test list, though!

2021-06-18 00:31 UTC, kenrussell commented
> You need to add it to the test list, though!

I had that in my local workspace, I swear! Not sure how I missed it.

2021-06-18 00:39 UTC, jdashg approved these changes

2021-06-18 00:39 UTC, merged