Markup definitions with their type
KhronosGroup/WebGL pull request #3294
Opened 2021-06-22 07:07 UTC by dontcallmedom

As defined in the [definition markup contract](https://tabatkins.github.io/bikeshed/#dfn-contract) that many Web specs are adhering to - these conventions are not specific to bikeshed (they are [being moved to a document on their own](https://github.com/tabatkins/bikeshed/issues/2088#issuecomment-864169459)).

Adhering to these conventions makes it easier for other specifications to reference items defined in WebGL, through projects such as [webref](github.com/w3c/webref/) and [shepherd](http://hg.csswg.org/dev/shepherd/) which themseves are integrated in bikeshed and respec, widely used by other specs.

If this type of changes are acceptable and welcome, I would be happy to provide additional patches for other IDL items, at least those that are known to be referenced from other specs - if so, I might need guidance on what convention to follow to assign `id`s to these definitions.

2021-06-22 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/WebGL?pullRequest=3294) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/WebGL?pullRequest=3294) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/WebGL?pullRequest=3294) it.</sub>

2021-06-23 16:32 UTC, kenrussell requested changes
Thanks for these improvements.

We'd be happy to integrate them but they should ideally be applied to the editors' drafts:

specs/latest/1.0/index.html
specs/latest/2.0/index.html

Would you make these changes there instead? Thanks in advance.

2021-06-23 16:51 UTC, kenrussell approved these changes
Thanks, looks good to me. Spec editor @jdashg should review this as well.

2021-06-29 06:01 UTC, jdashg approved these changes
Looks good to me!

2021-06-29 06:06 UTC, jdashg requested changes
Could you fix your commit message? An \`id` got executed/expanded in bash...

2021-06-29 06:13 UTC, jdashg approved these changes

2021-06-29 06:13 UTC, merged

2021-06-29 06:13 UTC, jdashg commented
Thanks!